---
- name: "Ensure /etc/letsencrypt/credentials.ini"
  template:
    dest: "/etc/letsencrypt/credentials.ini"
    src: "etc/letsencrypt/credentials.ini"
    mode: "500"
    owner: root
    group: root

- name: "Prepare extra domain names"
  set_fact:
    additional_domain_command: ""

- name: "Add extra domains to variable"
  set_fact:
    additional_domain_command: "{{ additional_domain_command }} -d {{ item }} -d *.{{item}}"
  with_items: "{{ additional_domains }}"

- name: "Run certbot challenges"
  command: "certbot certonly
    --agree-tos
    --dns-digitalocean
    -m {{ nginx_host_letsencrypt_email }}
    -d {{ '*.' + inventory_hostname }}
    -d {{ inventory_hostname }}
    {{ additional_domain_command }}
    --expand
    --dns-digitalocean-credentials=/etc/letsencrypt/credentials.ini
    -n"

- name: "Copy service and timer templates for certbot"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "644"
    owner: root
    group: root
  with_items:
    - { src: etc/systemd/system/certbot-renewal.service, dest: /etc/systemd/system/certbot-renewal.service }
    - { src: etc/systemd/system/certbot-renewal.timer, dest: /etc/systemd/system/certbot-renewal.timer }

- name: "Start and enable service"
  service:
    name: certbot-renewal.timer
    state: started
    enabled: yes

- name: "Ensure dhparam.pem"
  openssl_dhparam:
    path: "/etc/letsencrypt/live/{{ inventory_hostname }}/dhparam.pem"
    owner: root
    group: root
    size: 2048
